apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: licium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
        - name: drawio
          image: jgraph/drawio
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DRAWIO_BASE_URL
              value: /drawio
            - name: DRAWIO_SERVER_URL
              value: http://licium.domain.local/drawio
---
apiVersion: v1
kind: Service
metadata:
  name: drawio
  namespace: licium
spec:
  selector:
    app: drawio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
