apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuY29uYnJvLmxvY2FsIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlkwRjNjVzkzTFRab2IzSm1lUzF1YVhOamIzST0iCgkJfQoJfQp9
kind: Secret
metadata:
  name: regcred
  namespace: licium
type: kubernetes.io/dockerconfigjson
