{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "licium.fullname" . }}-limit-body-size
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "licium.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: 104857600
{{- end }}
