{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "licium.fullname" . }}-basic-auth
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "licium.labels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "licium.fullname" . }}-secrets
{{- end }}
