{{- if .Values.security.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "licium.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "licium.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.security.apiToken | quote }}
  basic-auth-users: {{ .Values.security.basicAuthUsers | quote }}
{{- end }}
